"""Runs every query in sql/analysis_queries.sql against data/fraud.db and writes
the results as a readable markdown report to reports/sql_findings.md."""
import sqlite3
import re
from pathlib import Path
import pandas as pd

conn = sqlite3.connect("data/fraud.db")
raw = Path("sql/analysis_queries.sql").read_text()

# split on our numbered "-- N. Title" comment headers
blocks = re.split(r"\n-- (\d+)\. ", raw)
header_pre, rest = blocks[0], blocks[1:]

out = ["# SQL Findings — Fraud Detection Engine\n",
       "Generated by `src/run_sql_report.py` against `data/fraud.db`.\n"]

for i in range(0, len(rest), 2):
    num, block = rest[i], rest[i + 1]
    title_line, _, sql_body = block.partition("\n")
    # strip trailing comment-only lines from sql, keep the statement
    sql = sql_body.strip()
    df = pd.read_sql_query(sql, conn)
    out.append(f"## {num}. {title_line.strip()}\n")
    out.append(df.to_markdown(index=False))
    out.append("\n")

Path("reports").mkdir(exist_ok=True)
Path("reports/sql_findings.md").write_text("\n".join(out), encoding="utf-8")
print("Wrote reports/sql_findings.md")
print("\n".join(out[:40]))
